global:
  scrape_interval: 10s 
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'model_metrics'
    static_configs:
      - targets: ['fastapi:8000']
    metrics_path: '/prometheus-metrics'
    scrape_interval: 10s
rule_files:
  - 'recording_rules.yml'
