global:
  scrape_interval: 10s 
  evaluation_interval: 15s
remote_write:
  - url: https://prometheus-prod-32-prod-ca-east-0.grafana.net/api/prom/push
scrape_configs:
  - job_name: 'model_metrics'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/prometheus-metrics'
    scrape_interval: 10s
rule_files:
  - 'recording_rules.yml'
