apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: bei5oywubbqwwd
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    uid: feh2mmi8gz7cwa
    url: http://fastapi:8000
    jsonData:
      global_queries: []